# Generated by Django 5.0.6 on 2026-06-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("importacoes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PontoAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Ponto"),
                ),
                (
                    "localizacao",
                    models.CharField(max_length=150, verbose_name="Localização"),
                ),
            ],
            options={
                "verbose_name": "Ponto de Acesso",
                "verbose_name_plural": "Pontos de Acesso",
            },
        ),
        migrations.CreateModel(
            name="RegistroAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador_pseudonimizado",
                    models.CharField(
                        max_length=255, verbose_name="Identificador Pseudonimizado"
                    ),
                ),
                (
                    "tipo_acesso",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=20,
                        verbose_name="Tipo de Acesso",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(verbose_name="Data e Hora do Acesso"),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_importados",
                        to="importacoes.importacao",
                        verbose_name="Importação Vinculada",
                    ),
                ),
                (
                    "ponto_acesso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="acessos.pontoacesso",
                        verbose_name="Ponto de Acesso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Acesso",
                "verbose_name_plural": "Registros de Acesso",
            },
        ),
    ]
