# Generated by Django 5.0.6 on 2026-06-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acessos", "0001_initial"),
        ("importacoes", "0002_remove_importacao_arquivo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoacesso",
            name="grupo_equipamento",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="registroacesso",
            name="evento",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="registroacesso",
            name="foto",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="registroacesso",
            name="tipo_consulta",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pontoacesso",
            name="localizacao",
            field=models.CharField(
                help_text="Área de Origem / Destino", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="pontoacesso",
            name="nome",
            field=models.CharField(help_text="Nome do Equipamento", max_length=100),
        ),
        migrations.AlterField(
            model_name="registroacesso",
            name="identificador_pseudonimizado",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="registroacesso",
            name="importacao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="importacoes.importacao",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registroacesso",
            name="ponto_acesso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="acessos.pontoacesso",
            ),
        ),
        migrations.AlterField(
            model_name="registroacesso",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="registroacesso",
            name="tipo_acesso",
            field=models.CharField(max_length=50),
        ),
    ]
