# Generated by Django 5.0.6 on 2026-06-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "acessos",
            "0002_pontoacesso_grupo_equipamento_registroacesso_evento_and_more",
        ),
        ("importacoes", "0002_remove_importacao_arquivo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "numero_credencial",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="número da credencial",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "estrutura_organizacional",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="estrutura organizacional",
                    ),
                ),
            ],
            options={
                "verbose_name": "pessoa",
                "verbose_name_plural": "pessoas",
            },
        ),
        migrations.CreateModel(
            name="RegraHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grupo_equipamento",
                    models.CharField(
                        help_text="Ex: PORTARIA, BIBLIOTECA",
                        max_length=100,
                        verbose_name="grupo do equipamento",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (1, "Domingo"),
                            (2, "Segunda-feira"),
                            (3, "Terça-feira"),
                            (4, "Quarta-feira"),
                            (5, "Quinta-feira"),
                            (6, "Sexta-feira"),
                            (7, "Sábado"),
                        ],
                        verbose_name="dia da semana",
                    ),
                ),
                ("horario_inicio", models.TimeField(verbose_name="horário de início")),
                ("horario_fim", models.TimeField(verbose_name="horário de fim")),
            ],
            options={
                "verbose_name": "regra de horário",
                "verbose_name_plural": "regras de horário",
                "ordering": ["grupo_equipamento", "dia_semana"],
            },
        ),
        migrations.AlterModelOptions(
            name="registroacesso",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Registro de Acesso",
                "verbose_name_plural": "Registros de Acesso",
            },
        ),
        migrations.AddField(
            model_name="registroacesso",
            name="area_destino",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="área de destino"
            ),
        ),
        migrations.AddField(
            model_name="registroacesso",
            name="area_origem",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="área de origem"
            ),
        ),
        migrations.AlterField(
            model_name="registroacesso",
            name="tipo_acesso",
            field=models.CharField(
                blank=True,
                choices=[("Entrada", "Entrada"), ("Saída", "Saída")],
                default="",
                max_length=50,
                verbose_name="direção do evento",
            ),
        ),
        migrations.AddIndex(
            model_name="registroacesso",
            index=models.Index(
                fields=["identificador_pseudonimizado", "timestamp"],
                name="idx_ident_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="registroacesso",
            index=models.Index(fields=["timestamp"], name="idx_timestamp"),
        ),
        migrations.AddIndex(
            model_name="registroacesso",
            index=models.Index(fields=["tipo_acesso"], name="idx_tipo_acesso"),
        ),
        migrations.AddConstraint(
            model_name="regrahorario",
            constraint=models.UniqueConstraint(
                fields=("grupo_equipamento", "dia_semana"), name="unique_grupo_dia"
            ),
        ),
    ]
