# Generated by Django 5.0.6 on 2026-07-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acessos", "0003_pessoa_regrahorario_alter_registroacesso_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroacesso",
            name="nome_cifrado",
            field=models.TextField(blank=True, default="", verbose_name="nome cifrado"),
        ),
    ]
