# Generated by Django 5.0.6 on 2026-07-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acessos", "0004_registroacesso_nome_cifrado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registroacesso",
            name="nome_cifrado",
        ),
    ]
