# Generated by Django 5.0.6 on 2026-07-14 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioGerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        help_text="Ex: Relatório de acessos, Resumo mensal",
                        max_length=100,
                        verbose_name="tipo de relatório",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("EXCEL", "Excel")],
                        max_length=10,
                        verbose_name="formato do arquivo",
                    ),
                ),
                (
                    "filtros",
                    models.JSONField(
                        help_text="Parâmetros escolhidos pelo usuário na geração (datas, pontos de acesso, etc.)",
                        verbose_name="filtros utilizados",
                    ),
                ),
                (
                    "data_geracao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de geração"
                    ),
                ),
                (
                    "caminho_arquivo",
                    models.CharField(max_length=255, verbose_name="caminho do arquivo"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relatorios_gerados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "relatório gerado",
                "verbose_name_plural": "relatórios gerados",
                "ordering": ["-data_geracao"],
            },
        ),
    ]
