services:
  db:
    image: postgres:16-alpine
    container_name: cac-db
    environment:
      POSTGRES_USER: cac_user
      POSTGRES_PASSWORD: cac_password
      POSTGRES_DB: cac_db
    ports:
      - "5433:5432"
    volumes:
      - cac_pgdata:/var/lib/postgresql/data

  web:
      build:
        context: .
        dockerfile: infra/Dockerfile
      container_name: cac_web
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      env_file:
        - .env
      environment:
        - DATABASE_URL=postgres://cac_user:cac_password@db:5432/cac_db
      depends_on:
        - db

volumes:
  cac_pgdata: