# Generated by Django 5.0.6 on 2026-06-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Importacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="importacoes/", verbose_name="Arquivo CSV"
                    ),
                ),
                (
                    "data_importacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Importação"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="concluido", max_length=50, verbose_name="Status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Importação",
                "verbose_name_plural": "Importações",
            },
        ),
    ]
