# Generated by Django 5.0.6 on 2026-06-06 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importacoes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importacao",
            name="arquivo",
        ),
        migrations.RemoveField(
            model_name="importacao",
            name="data_importacao",
        ),
        migrations.RemoveField(
            model_name="importacao",
            name="status",
        ),
        migrations.AddField(
            model_name="importacao",
            name="dados_brutos",
            field=models.TextField(
                blank=True, help_text="Linha do CSV em caso de erro", null=True
            ),
        ),
        migrations.AddField(
            model_name="importacao",
            name="data_tentativa",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="importacao",
            name="linha_arquivo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importacao",
            name="motivo_erro",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="importacao",
            name="nome_arquivo",
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
