# Generated by Django 5.0.6 on 2026-06-14 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importacoes", "0002_remove_importacao_arquivo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="importacao",
            name="arquivo",
            field=models.FileField(default="", upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="importacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCESSO", "Sucesso"),
                    ("FALHA", "Falha"),
                    ("PROCESSANDO", "Processando"),
                ],
                default="PROCESSANDO",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="importacao",
            name="total_registros",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importacao",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
