# Generated by Django 5.0.6 on 2026-06-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importacoes", "0003_importacao_arquivo_importacao_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importacao",
            name="total_duplicados",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importacao",
            name="total_invalidos",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importacao",
            name="total_validos",
            field=models.IntegerField(default=0),
        ),
    ]
