# Generated by Django 5.0.6 on 2026-06-25 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importacoes", "0004_importacao_total_duplicados_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FalhaImportacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linha_arquivo", models.IntegerField(verbose_name="Linha do Arquivo")),
                ("motivo_erro", models.TextField(verbose_name="Motivo do Erro")),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="falhas",
                        to="importacoes.importacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Falha na Importação",
                "verbose_name_plural": "Falhas nas Importações",
                "ordering": ["linha_arquivo"],
            },
        ),
    ]
