# Generated by Django 5.0.6 on 2026-07-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="data do evento")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("volume_atipico", "Volume atípico"),
                            ("fora_de_horario", "Acesso fora do horário"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "valor",
                    models.FloatField(
                        help_text="Volume observado no dia (ou nº de acessos fora do horário)."
                    ),
                ),
                ("detalhe", models.CharField(blank=True, default="", max_length=200)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "alerta",
                "verbose_name_plural": "alertas",
                "ordering": ["-data", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="ChaveAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Quem usa esta chave (ex.: 'Painel da reitoria').",
                        max_length=100,
                    ),
                ),
                ("prefixo", models.CharField(editable=False, max_length=12)),
                (
                    "chave_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("ativa", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ultimo_uso",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "verbose_name": "chave de API",
                "verbose_name_plural": "chaves de API",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddConstraint(
            model_name="alerta",
            constraint=models.UniqueConstraint(
                fields=("data", "tipo"), name="unique_alerta_data_tipo"
            ),
        ),
    ]
