# Generated by Django 5.0.6 on 2026-07-29 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acessos", "0007_remover_identificador_pseudonimizado"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="alerta",
            name="unique_alerta_data_tipo",
        ),
        migrations.AddField(
            model_name="alerta",
            name="registro",
            field=models.ForeignKey(
                blank=True,
                help_text="Acesso que gerou a anomalia. Nulo em anomalias do dia inteiro.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertas",
                to="acessos.registroacesso",
            ),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("volume_atipico", "Volume atípico"),
                    ("fora_de_horario", "Acesso fora do horário"),
                    ("acesso_repetido", "Acesso repetido em sequência"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="valor",
            field=models.FloatField(
                help_text="Volume do dia, ou o intervalo em segundos do acesso repetido."
            ),
        ),
        migrations.AddConstraint(
            model_name="alerta",
            constraint=models.UniqueConstraint(
                condition=models.Q(("registro__isnull", True)),
                fields=("data", "tipo"),
                name="unique_alerta_diario",
            ),
        ),
        migrations.AddConstraint(
            model_name="alerta",
            constraint=models.UniqueConstraint(
                condition=models.Q(("registro__isnull", False)),
                fields=("registro", "tipo"),
                name="unique_alerta_por_registro",
            ),
        ),
    ]
