# Generated by Django 5.0.6 on 2026-07-29 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acessos", "0007_remover_identificador_pseudonimizado"),
        ("analytics", "0002_remove_alerta_unique_alerta_data_tipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerta",
            name="registro_anterior",
            field=models.ForeignKey(
                blank=True,
                help_text="Acesso imediatamente antes, no acesso repetido. Guardado para contar quantas passagens distintas formaram a sequência.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas_como_anterior",
                to="acessos.registroacesso",
            ),
        ),
    ]
